### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by gaowanliang** [avinashpaliwal/Super-SloMo#14]
python video_to_slomo.py --ffmpeg D:\program_data\python\Super-SloMo\path\to\ffmp
eg\bin --video D:\program_data\python\Super-SloMo\path\to\123.mp4 --sf 3 --checkpoint D:\program_data\python\Super-SloMo
\path\to\checkpoint.ckpt --fps 72 --batch_size 1 --output D:\program_data\python\Super-SloMo\path\to\output.mp4
```
D:\program_data\python\Super-SloMo\path\to\ffmpeg\bin\ffmpeg -i D:\program_data\python\Super-SloMo\path\to\123.mp4 -vsync 0 -qscale:v 2 tmpSuperSloMo\input/%06d.jpg
ffmpeg version N-91520-gbce4da85e8 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 21.106 / 58. 21.106
  libavformat    58. 17.101 / 58. 17.101
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 26.100 /  7. 26.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\program_data\python\Super-SloMo\path\to\123.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomM4A
    creation_time   : 2019-01-04T08:31:32.000000Z
    iTunSMPB        :  00000000 00000A40 000003AC 000000000003BA14 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    encoder         : Nero AAC codec / 1.5.4.0
  Duration: 00:00:05.16, start: 0.000000, bitrate: 3156 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 1920x1080, 3061 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2019-01-04T08:31:32.000000Z
      handler_name    : L-SMASH Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 132 kb/s (default)
    Metadata:
      creation_time   : 2019-01-04T08:31:32.000000Z
      handler_name    : Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 00000194fd361f80] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'tmpSuperSloMo\input/%06d.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomM4A
    iTunSMPB        :  00000000 00000A40 000003AC 000000000003BA14 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    encoder         : Lavf58.17.101
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2019-01-04T08:31:32.000000Z
      handler_name    : L-SMASH Video Media Handler
      encoder         : Lavc58.21.106 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=  122 fps=0.0 q=2.0 Lsize=N/A time=00:00:05.08 bitrate=N/A speed=6.92x
video:28266kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Traceback (most recent call last):
  File "video_to_slomo.py", line 209, in <module>
    main()
  File "video_to_slomo.py", line 158, in main
    flowOut = flowComp(torch.cat((I0, I1), dim=1))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\program_data\python\Super-SloMo\model.py", line 199, in forward
    s2 = self.down1(s1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\program_data\python\Super-SloMo\model.py", line 71, in forward
    x = F.leaky_relu(self.conv2(x), negative_slope = 0.1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
```
my GPU is GTX 1060

**Comment by deama** [comment]
Strange, 1080p videos work for me (though they take forever lol); this is with a 970gtx.

**Comment by deama** [comment]
How did you install this? Did you use anaconda? What version? What installation commands did you run?

**Comment by avinashpaliwal** [comment]
It also depends on the `--sf` value you are passing. Try running the script at lower video resolution.

**Comment by avinashpaliwal** [comment]
Also at higher resolutions, there will be more motion in terms of pixels for the same objects. Large motions are challenging for this CNN.

**Comment by avinashpaliwal** [comment]
I am assuming that the issue is fixed and closing the issue.
