### ISSUE TITLE
CUDA out of memory when training a model to .ckpt?

### ISSUE THREAD

**Issue by deama** [avinashpaliwal/Super-SloMo#16]
So I'm trying to train my own custom model but am getting an out of memory error:
```
(base) C:\Users\deama\Desktop\Super-SloMo-master>python train.py --dataset_root
dataset --checkpoint_dir checkpoints
Dataset SuperSloMo
    Number of datapoints: 558
    Root Location: dataset/train
    Transforms (if any): Compose(
                             ToTensor()
                             Normalize(mean=[0.429, 0.431, 0.397], std=[1, 1, 1]
)
                         )
 Dataset SuperSloMo
    Number of datapoints: 5
    Root Location: dataset/validation
    Transforms (if any): Compose(
                             ToTensor()
                             Normalize(mean=[0.429, 0.431, 0.397], std=[1, 1, 1]
)
                         )

Epoch:  0
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:2423: UserWarn
ing: Default upsampling behavior when mode=bilinear is changed to align_corners=
False since 0.4.0. Please specify align_corners=True if the old behavior is desi
red. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "train.py", line 253, in <module>
    intrpOut = ArbTimeFlowIntrp(torch.cat((I0, I1, F_0_1, F_1_0, F_t_1, F_t_0, g
_I1_F_t_1, g_I0_F_t_0), dim=1))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\deama\Desktop\Super-SloMo-master\model.py", line 207, in forwar
d
    x  = self.up4(x, s2)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\deama\Desktop\Super-SloMo-master\model.py", line 134, in forwar
d
    x = F.leaky_relu(self.conv2(torch.cat((x, skpCn), 1)), negative_slope = 0.1)

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py",
line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", li
ne 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 45.38 MiB (GPU 0; 4.00 GiB t
otal capacity; 3.46 GiB already allocated; 118.97 MiB free; 47.47 MiB cached)
```

Is the only fix to get a GPU with more VRAM or use lower resolution training data? I have used the adobe240fps dataset provided.

**Comment by deama** [comment]
EDIT: It seems it gives me the same error even if I use 420p (ish) clips...

**Comment by avinashpaliwal** [comment]
There are two parts to data preparation:
1. If you have used the [create_dataset.py](https://github.com/avinashpaliwal/Super-SloMo/blob/master/data/create_dataset.py) as is, then it converts your video to 360p images by default (Unless you pass command-line arguments to change that). So regardless of the original video resolution, your training dataset will be 360p.
2. As part of the pre-processing in the dataloader, the images are by default cropped to dimensions (352, 352). So even if you have a custom dataset, the input by default will be a (352, 352) patch.

By default the training and validation batch size is set to 6 and 10. This works for 1080 Ti, but you should try reducing this parameter for the memory issue. You can do that by using `--train_batch_size` and `--validation_batch_size` command-line arguments for [train.py](https://github.com/avinashpaliwal/Super-SloMo/blob/master/train.py).

**Comment by deama** [comment]
Ah thanks, it works, for reference, I used:
--train_batch_size 3 --validation_batch_size 5
