### ISSUE TITLE
How to reduce the memory use?

### ISSUE THREAD

**Issue by AceSix** [avinashpaliwal/Super-SloMo#40]
When I try to transfer a short mp4 video of 1920*1080, 5 secs, there will be cuda runtime error. If I run it on CPU, the memory is still not enough.

**Comment by avinashpaliwal** [comment]
What do you mean by transfer? If you are running the slomo script, try reducing the resolution / number of frames interpolated. Check if it works with 720p resolution. Length of the video will affect the total time for conversion.

**Comment by Thomasedv** [comment]
Not sure if it would help, i'm completely new to pytorch and anything of the sort. I had a lot of near instant memory errors on a particular video, (1440p resolution)
So i added some `torch.cuda.empty_cache` calls before and after the call (in the file `video_to_slomo.py)` that gave me memory error. Which made my clip reach 6% instead of 1%, before hitting the memory error again. So then i added some at the start of the outer loop, right before the inner loop starts, and and after the inner loop ends, and also a time.sleep(0.1) just before the line that gives me memory errors.
I'm not sure what part of it helps, and i'm sure the time.sleep(0.1) might be stupid (the reasoning i used was that the cache might not clear fast enough)

But now at least, it's working for that clip, so i'm very happy at least.  (Well, results from using the pre-trained package does not work well for game clips. So limited happiness)

**Comment by lingfei1998** [comment]
I am running eval.py in the CPU environment and there is also a problem with insufficient memory, which directly causes my computer to crash.
During the debugging process, I found that the problem occurred in line 167 of model.py. When calculating the convolution, my RAM (8GB) reached 100%. How can I solve this problem? Thank you

**Comment by peterlabuschagne** [comment]
I also have a similar error with a 1080p video of 1 second in length. I have tested it for a video at 480p and it works with less than 10% of my GPU processing and memory being utilized when the slomo video is generated. I tried adding the torch.cuda.empty_cache() in every line that the RuntimeError: CUDA error: out of memory occurs, but still no luck. Is it possible to do 1080p video? I have a GTX1050 4GB with an additional 8GB shared memory.

**Comment by Thomasedv** [comment]
@peterlabuschagne It's likely not enough memory. It seems to only use the non-shared GPU memory, and my 1440p videos seem to be right around 10 GB where i got 11GB of memory. I seem to just have cut it after clearing the memory between the memory intensive operations.

**Comment by peterlabuschagne** [comment]
@Thomasedv Thanks for the info!
