### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Fried-Penguin-Wings** [avinashpaliwal/Super-SloMo#55]
**Describe the bug**
After running script, Error "cuDNN error: CUDNN_STATUS_EXECUTION_FAILED" appears. 

**To Reproduce**
Run script

**Expected behavior**
Generate video with 120fps

**Interpolated results/error output**

(base) C:\Users\Amos\SloMo\SuperSloMo>python video_to_slomo.py --ffmpeg C:\Users\Amos\SloMo\ffmpeg\bin\ --video C:\Users\Amos\SloMo\Input\beachvideo.mp4 --sf 5 --checkpoint C:\Users\Amos\SloMo\SuperSloMo\SuperSloMo.ckpt --fps 120 --output C:\Users\Amos\SloMo\Output\beachvideo120.mp4 --batch_size 1
C:\Users\Amos\SloMo\ffmpeg\bin\ffmpeg -i C:\Users\Amos\SloMo\Input\beachvideo.mp4 -vsync 0 -qscale:v 2 tmpSuperSloMo\input/%06d.jpg
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190716
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Amos\SloMo\Input\beachvideo.mp4':
  Metadata:
    major_brand     : 3gp5
    minor_version   : 0
    compatible_brands: 3gp5isom
    creation_time   : 2018-07-27T13:58:06.000000Z
    location        : +30.2159-085.8796/
    location-eng    : +30.2159-085.8796/
  Duration: 00:00:15.70, start: 0.000000, bitrate: 35206 kb/s
    Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/smpte170m), 3840x2160, 35074 kb/s, 30 fps, 30 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2018-07-27T13:58:06.000000Z
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 124 kb/s (default)
    Metadata:
      creation_time   : 2018-07-27T13:58:06.000000Z
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0000016d53584240] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'tmpSuperSloMo\input/%06d.jpg':
  Metadata:
    major_brand     : 3gp5
    minor_version   : 0
    compatible_brands: 3gp5isom
    location-eng    : +30.2159-085.8796/
    location        : +30.2159-085.8796/
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 3840x2160, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2018-07-27T13:58:06.000000Z
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=  471 fps= 35 q=2.0 Lsize=N/A time=00:00:15.70 bitrate=N/A speed=1.18x
video:268721kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
  0%|                                                                                          | 0/470 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "video_to_slomo.py", line 216, in <module>
    main()
  File "video_to_slomo.py", line 165, in main
    flowOut = flowComp(torch.cat((I0, I1), dim=1))
  File "C:\Users\Amos\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Amos\SloMo\SuperSloMo\model.py", line 197, in forward
    x  = F.leaky_relu(self.conv1(x), negative_slope = 0.1)
  File "C:\Users\Amos\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Amos\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Desktop (please complete the following information):**
 - OS: Windows
 - Device Used GPU
 - Setup Info [e.g. PyTorch 1.1, CUDA 9.0, Python 3.7

**Additional context**

**Comment by Siemko** [comment]
You mixed both options: `-sf` and `-fps`, try only `-sf` or only `-fps`.

**Comment by Fried-Penguin-Wings** [comment]
I'll give it that a shot. Thanks.

**Comment by Fried-Penguin-Wings** [comment]
No dice. It asking for both a variable for the slow motion factor and a variable for the target fps.

**Comment by Fried-Penguin-Wings** [comment]
I can run the command without the target fps argument, and it'll attempt it, but still results in the same error message.

**Comment by avinashpaliwal** [comment]
Can you try using pyTorch 0.4.1 and CUDA 9.2. This was the setup used for training and testing.

**Comment by CM-BF** [comment]
That is the inconsistence of your pytorch version and your CUDA version. As the author, try using pyTorch0.4.1 and CUDA 9.x or just using pyTorch1.1 and CUDA 10.1(it can work fine, too).

**Comment by Fried-Penguin-Wings** [comment]
Thanks. I'll give it a shot today.

**Comment by Fried-Penguin-Wings** [comment]
That did the trick. Thanks!
