### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by mrtajniak** [avinashpaliwal/Super-SloMo#58]
after frequent use there was an error "CUDA out of memory" I tried to change BrenchSize but it didn't help, it could use a GPU cache cleaner

**Comment by saturn118** [comment]
I'm also getting this error. Any updates?

**Comment by Fried-Penguin-Wings** [comment]
I'm getting this error on certain videos as well.

**Comment by Fried-Penguin-Wings** [comment]
Eval for me.

**Comment by partajmannen2** [comment]
I'm also getting this error whenever I process any footage above 1080p. I'm using a gtx 1070 with 8GB VRAM.

**Comment by avinashpaliwal** [comment]
I don't think we can do much for resolutions above 1080p. Since there are two CNNs, we can run the first CNN, generate the intermediate outputs and then run the second CNN or some other approach. This will take time.

**Comment by Thomasedv** [comment]
Just as potential suggestion, i made a comment in another issue. I managed to do 1440p video with a GTX 1080TI with 11 GB of Memory, by adding some cache emptying steps. I wouldn't go as far as to litter the code with these, but if a user wants to try to push the limit, this might just cut it. 

https://github.com/avinashpaliwal/Super-SloMo/issues/40#issuecomment-488127868

**Comment by avinashpaliwal** [comment]
@Thomasedv . You are right. I have used it in some other pyTorch code and though it fixes the memory issue, it also make the eval slower. I can add a flag for this. Also this code was not trained on high resolution videos, so it may not perform well at resolutions like 1440p.

**Comment by gamesmusic454** [comment]
Hello, im having the same memory issues that they mentioned before, i have a r6 3700x and a gtx 1060 6GB, with 8 GB of ram for the system(temporal), and i always receive the same exact message. 
![Sin título](https://user-images.githubusercontent.com/43968446/71754539-e6bf1800-2e86-11ea-8b34-ca733840249c.jpg)

**Comment by s-a** [comment]
Just cloned fresh this repository. It works for me with a lower resolution (geforce 940m). Lowest resolution I can process is (1280 x 720). Any news on this topic?
